version: '3.3'
services:
  apache:
    image: httpd:latest
    volumes:
      - ./datos-reto/web/:/usr/local/apache2/htdocs/
    ports:
      #puertos
      - "8081:80"
  nginx:
    image: nginx:latest
    volumes:
      - ./datos-reto/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  data-feeder:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8085:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=Leire
      - DB_PASSWORD=12345678
      - DB_DATABASE=Leire
    volumes:
      - './datos-reto/data-feeder:/app'
    command: [ "php", "artisan", "schedule:work" ]
    depends_on:
             mysql:
                condition: service_healthy
  opencast-api:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8086:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=Leire
      - DB_PASSWORD=12345678
      - DB_DATABASE=Leire
    volumes:
      - './datos-reto/opencast-api:/app'
    command: ["sh", "-c", "php artisan migrate && php artisan passport:install --force && php artisan serve --host=0.0.0.0"]
    depends_on:
             mysql:
                condition: service_healthy
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'Leire'
      MYSQL_USER: 'Leire'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - './datos-reto/mysql/:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8084:80"
    environment:
      - PMA_ARBITRARY=1
